name: Publish to NPM

on:
  push:
    branches:
      - main  # Cambia esto por el nombre de tu rama principal si es diferente

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}  # Asegúrate de configurar este secreto en la configuración de tu repositorio
        run: npm publish --access public  # Cambia '--access public' si tu paquete es privado
